# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tds2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QFileDialog, QPushButton, QMenu, QAction, QMessageBox, QDialog, QVBoxLayout,QTextEdit, QLabel, QLineEdit, QTabWidget, QGridLayout
from PyQt5.QtCore import QFile, QTextStream, QThreadPool, QJsonDocument
from PyQt5 import QtCore
from PyQt5.QtCore import Qt
import threading
import requests
from tiktok import SeleniumWorker
import time
import traceback
from PyQt5.QtGui import QPixmap, QIntValidator
from pathlib import Path
import json
import os
from proxy_chrome_driver import get_chromedriver
from tiktok_socket import TiktokSocketWorker

class PasswordDelegate(QtWidgets.QStyledItemDelegate):
    def initStyleOption(self, option, index):
        super().initStyleOption(option, index)
        style = option.widget.style() or QtWidgets.QApplication.style()
        hint = style.styleHint(QtWidgets.QStyle.SH_LineEdit_PasswordCharacter)
        option.text = chr(hint) * len(option.text)

class AddCategoryDialog(QDialog):
    def __init__(self, parent=None):
        super(AddCategoryDialog, self).__init__(parent)
        self.setWindowTitle("Add new category")
        self.setGeometry(400, 200, 300, 100)

        self.label = QLabel("Nhập category mới:")
        self.text_input = QLineEdit(self)
        self.ok_button = QPushButton("Lưu", self)

        layout = QVBoxLayout(self)
        layout.addWidget(self.label)
        layout.addWidget(self.text_input)
        layout.addWidget(self.ok_button)

        self.ok_button.clicked.connect(self.accept)
    
class RemoveCategoryDialog(QDialog):
    def __init__(self, parent=None):
        super(AddCategoryDialog, self).__init__(parent)
        self.setWindowTitle("Add new category")
        self.setGeometry(400, 200, 300, 100)

        self.label = QLabel("Nhập category mới:")
        self.text_input = QLineEdit(self)
        self.ok_button = QPushButton("Lưu", self)

        layout = QVBoxLayout(self)
        layout.addWidget(self.label)
        layout.addWidget(self.text_input)
        layout.addWidget(self.ok_button)

        self.ok_button.clicked.connect(self.accept)

class Ui_MainWindow(object):

    def __init__(self):
        self.column_order = ["username", "password","email", "email_password", "cookie", "token", "profile_status", "proxy", "status"]

        self.accounts = {}
        
        self.base_url = "https://traodoisub.com"

        # New
        # self.threadpool = QThreadPool()
        self.threadpool = QThreadPool()
        # Set the maximum number of threads (workers)
        self.threadpool.setMaxThreadCount(4)
        print("Multithreading with maximum %d threads" % self.threadpool.maxThreadCount())

        # New
        self.check_mark_img = './images/check-mark-16.jpg'
        self.x_mark_img = './images/x-mark-16.jpg'

        # New - 1/1/2024
        self.selected_rows_count = 0
        self.running_threads = 0
        self.waiting_threads = 0
        self.completed_threads = 0


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")

        # Size of the main window
        MainWindow.resize(1690, 900)


        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # NEW TAB
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1739, 1100))
        self.tabWidget.setObjectName("tabWidget")

        self.actionTab = QtWidgets.QWidget()
        self.actionTab.setObjectName("actionTab")


        self.addAccountButton = QtWidgets.QPushButton(self.actionTab)
        self.addAccountButton.setGeometry(QtCore.QRect(28, 20, 101, 31))
        self.addAccountButton.setObjectName("addAccountButton")

        self.addProxyButton = QtWidgets.QPushButton(self.actionTab)
        self.addProxyButton.setGeometry(QtCore.QRect(130, 20, 101, 31))
        self.addProxyButton.setObjectName("addProxyButton")

        # NEW
        self.saveProfiles = QtWidgets.QPushButton(self.actionTab)
        self.saveProfiles.setGeometry(QtCore.QRect(232, 20, 101, 31))
        self.saveProfiles.setObjectName("saveProfiles")

        # self.importConfig = QtWidgets.QPushButton(self.centralwidget)
        # self.importConfig.setGeometry(QtCore.QRect(334, 20, 101, 31))
        # self.importConfig.setObjectName("importConfig")

        self.interactTiktok = QtWidgets.QPushButton(self.actionTab)
        self.interactTiktok.setGeometry(QtCore.QRect(334, 20, 101, 31))
        self.interactTiktok.setObjectName("interactTiktok")


        

        self.tableWidget = QtWidgets.QTableWidget(self.actionTab)
        # 3rd and 4th parameters use to set width and height of the Table Widget
        self.tableWidget.setGeometry(QtCore.QRect(30, 130, 1616, 639))


        self.tableWidget.setObjectName("tableWidget")

        # Set column count
        self.tableWidget.setColumnCount(10)

        # self.tableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()

        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)

        # set all column width
        # self.set_column_width()


        # Set specified width for column "Username"
        self.tableWidget.setColumnWidth(0, 129)

        # Set specified width for column "Password"
        self.tableWidget.setColumnWidth(1, 129)

        # Set specified width for column "Email"
        self.tableWidget.setColumnWidth(2, 200)

        # Set specified width for column "Email Password"
        self.tableWidget.setColumnWidth(3, 129)

        # Set specified width for column "Cookie"
        self.tableWidget.setColumnWidth(4, 129)

        # Set specified width for column "Token"
        self.tableWidget.setColumnWidth(5, 129)

        # Set specified width for column "Profile Status"
        self.tableWidget.setColumnWidth(6, 129)

        # Set specified width for column "proxy"
        self.tableWidget.setColumnWidth(7, 134)

        # Set specified width for column "received jobs"
        self.tableWidget.setColumnWidth(8, 123)


        # Set specified width for column "status"
        self.tableWidget.setColumnWidth(9, 360)


        # Set row height
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)

        # Label "File:""
        self.filterLabel = QtWidgets.QLabel(self.actionTab)
        self.filterLabel.setGeometry(QtCore.QRect(30, 90, 20, 16))
        self.filterLabel.setObjectName("filterLabel")

        # Combobox "category"
        self.category = QtWidgets.QComboBox(self.actionTab)
        self.category.setGeometry(QtCore.QRect(54, 89, 120, 21))
        self.category.setObjectName("category")
        self.category.addItem("All category")

        # Button choose category options
        self.categoryOptions = QtWidgets.QPushButton(self.actionTab)
        self.categoryOptions.setGeometry(QtCore.QRect(179, 91, 20, 18))
        self.categoryOptions.setObjectName("categoryOptions")

        # NEW 6/1
        self.widget = QtWidgets.QWidget(self.actionTab)
        self.widget.setGeometry(QtCore.QRect(180, 110, 109, 58))
        self.widget.setObjectName("widget")
        self.widget.setStyleSheet("background-color: #eeeee4;")
        self.AddCategory = QtWidgets.QPushButton(self.widget)
        self.AddCategory.setGeometry(QtCore.QRect(5, 4, 99, 23))
        self.AddCategory.setObjectName("AddCategory")
        self.AddCategory.setStyleSheet("background-color: white;")
        self.RemoveCategory = QtWidgets.QPushButton(self.widget)
        self.RemoveCategory.setGeometry(QtCore.QRect(5, 29, 99, 23))
        self.RemoveCategory.setObjectName("RemoveCategory")
        self.RemoveCategory.setStyleSheet("background-color: white;")

        # Label "Total selected rows:"
        self.totalSelectedRows = QtWidgets.QLabel(self.actionTab)
        self.totalSelectedRows.setGeometry(QtCore.QRect(30, 779, 741, 16))
        self.totalSelectedRows.setObjectName("totalSelectedRows")

        # Label "Total selected rows:"
        self.totalRunningRows = QtWidgets.QLabel(self.actionTab)
        self.totalRunningRows.setGeometry(QtCore.QRect(30, 799, 741, 16))
        self.totalRunningRows.setObjectName("totalRunningRows")

        # Label "Total selected rows:"
        self.totalWaitingRows = QtWidgets.QLabel(self.actionTab)
        self.totalWaitingRows.setGeometry(QtCore.QRect(30, 819, 741, 16))
        self.totalWaitingRows.setObjectName("totalWaitingRows")

        # Label "Total selected rows:"
        self.totalCompletedRows = QtWidgets.QLabel(self.actionTab)
        self.totalCompletedRows.setGeometry(QtCore.QRect(30, 839, 741, 16))
        self.totalCompletedRows.setObjectName("totalCompletedRows")

        MainWindow.setCentralWidget(self.actionTab)

        # NEW - Right click menu
        self.tableWidget.setContextMenuPolicy(Qt.CustomContextMenu)
        self.tableWidget.customContextMenuRequested.connect(self.showContextMenu)


        # new
        self.addAccountButton.clicked.connect(self.show_add_accounts_dialog)
        self.addProxyButton.clicked.connect(self.show_add_proxies_dialog)
        self.saveProfiles.clicked.connect(self.save_profiles)
        self.interactTiktok.clicked.connect(self.interact_tiktok)
        
        # New 6/1
        self.category.currentTextChanged.connect(self.update_table)
        self.categoryOptions.clicked.connect(self.toggle_category_options)
        self.AddCategory.clicked.connect(self.show_add_new_category)
        self.RemoveCategory.clicked.connect(self.show_confirm_remove_category)
        # New
        self.tempTableWidget = QtWidgets.QTableWidget()
        self.tabWidget.addTab(self.actionTab, "")

        # TAB CONFIG TIKTOK JOB
        self.jobConfiguration = QtWidgets.QWidget()
        self.jobConfiguration.setObjectName("jobConfiguration")
        self.livestreamLabel = QtWidgets.QLabel(self.jobConfiguration)
        self.livestreamLabel.setGeometry(QtCore.QRect(30, 30, 101, 16))
        self.livestreamLabel.setObjectName("livestreamLabel")

        self.livestreamIdEdit = QtWidgets.QLineEdit(self.jobConfiguration)
        self.livestreamIdEdit.setGeometry(QtCore.QRect(130, 30, 140, 20))
        self.livestreamIdEdit.setObjectName("lineEdit")
        
        self.reLivestreamLabel = QtWidgets.QLabel(self.jobConfiguration)
        self.reLivestreamLabel.setGeometry(QtCore.QRect(280, 30, 91, 16))
        self.reLivestreamLabel.setObjectName("reLivestreamLabel")
        self.reLivestreamIdEdit = QtWidgets.QLineEdit(self.jobConfiguration)
        self.reLivestreamIdEdit.setGeometry(QtCore.QRect(370, 30, 140, 20))
        self.reLivestreamIdEdit.setObjectName("livestreamIdEdit")

        self.delayTimeLabel = QtWidgets.QLabel(self.jobConfiguration)
        self.delayTimeLabel.setGeometry(QtCore.QRect(520, 30, 61, 16))
        self.delayTimeLabel.setObjectName("delayTimeLabel")

        self.delayTimeEdit = QtWidgets.QLineEdit(self.jobConfiguration)
        self.delayTimeEdit.setGeometry(QtCore.QRect(584, 30, 51, 20))
        self.delayTimeEdit.setObjectName("delayTimeEdit")

        self.commentTable = QtWidgets.QTableWidget(self.jobConfiguration)
        self.commentTable.setGeometry(QtCore.QRect(30, 100, 1021, 431))
        self.commentTable.setObjectName("commentTable")
        self.commentTable.setColumnCount(3)
        self.commentTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.commentTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.commentTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.commentTable.setHorizontalHeaderItem(2, item)
        self.tabWidget.addTab(self.jobConfiguration, "")



        

        # TAB TIKTOK INTERACTIONS (throw heart)
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.t3LiveSrcLabel = QtWidgets.QLabel(self.tab_3)
        self.t3LiveSrcLabel.setGeometry(QtCore.QRect(10, 30, 100, 16))
        self.t3LiveSrclineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.t3LiveSrclineEdit.setGeometry(QtCore.QRect(110, 30, 113, 20))
        self.t3LiveSrclineEdit.setObjectName("lineEdit")
        self.t3WorkTimeLabel = QtWidgets.QLabel(self.tab_3)
        self.t3WorkTimeLabel.setGeometry(QtCore.QRect(240, 30, 86, 16))
        self.t3WorkTimeLabel.setObjectName("t3WorkTimeLabel")
        self.t3WorkTimelineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.t3WorkTimelineEdit.setGeometry(QtCore.QRect(328, 30, 39, 20))
        self.t3WorkTimelineEdit.setObjectName("t3WorkTimelineEdit")
        self.t3LiveStatusLabel = QtWidgets.QLabel(self.tab_3)
        self.t3LiveStatusLabel.setGeometry(QtCore.QRect(390, 30, 55, 16))
        self.t3LiveStatusLabel.setObjectName("t3LiveStatusLabel")
        self.t3LiveStatusLineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.t3LiveStatusLineEdit.setGeometry(QtCore.QRect(448, 30, 300, 20))
        self.t3LiveStatusLineEdit.setObjectName("t3WorkTimelineEdit")
        self.t3LiveStatusLineEdit.setEnabled(False)
        self.t3SaveConfigBtn = QtWidgets.QPushButton(self.tab_3)
        self.t3SaveConfigBtn.setGeometry(QtCore.QRect(900, 30, 51, 23))
        self.t3SaveConfigBtn.setObjectName("t3SaveConfigBtn")
        self.t3tableWidget = QtWidgets.QTableWidget(self.tab_3)
        self.t3tableWidget.setGeometry(QtCore.QRect(10, 68, 941, 680))
        self.t3tableWidget.setObjectName("t3tableWidget")
        self.t3tableWidget.setColumnCount(3)
        self.t3tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.t3tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.t3tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.t3tableWidget.setHorizontalHeaderItem(2, item)
        self.t3tableWidget.setColumnWidth(0, 200)
        self.t3tableWidget.setColumnWidth(1, 200)
        self.t3tableWidget.setColumnWidth(2, 523)

        self.t3SaveConfigBtn.clicked.connect(self.t3_saveConfig)

        self.tabWidget.addTab(self.tab_3, "")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1064, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TIKTOK"))
        self.addAccountButton.setText(_translate("MainWindow", "Thêm tài khoản"))
        self.addProxyButton.setText(_translate("MainWindow", "Thêm proxy"))
        self.categoryOptions.setText(_translate("MainWindow", "..."))

        self.saveProfiles.setText(_translate("MainWindow", "Tạo profile"))
        self.interactTiktok.setText(_translate("MainWindow", "Tương tác"))

        # new 6/1
        self.AddCategory.setText(_translate("MainWindow", "Add category"))
        self.RemoveCategory.setText(_translate("MainWindow", "Remove category"))


        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Username"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Password"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Email_password"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Cookie"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Token"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Profile Status"))


        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Proxy"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Received Jobs"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Status"))

        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)

        self.filterLabel.setText(_translate("MainWindow", "Lọc:"))

        # NEW
        self.totalSelectedRows.setText(_translate("MainWindow", f"(*) Selected accounts: {self.selected_rows_count}"))
        self.totalRunningRows.setText(_translate("MainWindow", f"Running accounts: {self.running_threads}"))
        self.totalWaitingRows.setText(_translate("MainWindow", f"Waiting accounts: {self.waiting_threads}"))
        self.totalCompletedRows.setText(_translate("MainWindow", f"Completed accounts: {self.completed_threads}"))

        self.tableWidget.itemSelectionChanged.connect(self.updateSelectedRows)

        self.accounts['All category'] = []

        self.widget.hide()

        # NEW 12.1.2024
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.actionTab), _translate("MainWindow", "Thao tác"))

        # NEW
        # Load defaut data when startup
        # self.load_default_data()

        # RESTRANLATE FOR TAB CONFIG
        self.livestreamLabel.setText(_translate("MainWindow", "Livestream (nguồn):"))
        self.reLivestreamLabel.setText(_translate("MainWindow", "Livestream (reup):"))
        self.delayTimeLabel.setText(_translate("MainWindow", "Time (delay):"))
        item = self.commentTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Comment"))
        item = self.commentTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Retrieved At"))
        item = self.commentTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Status"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.jobConfiguration), _translate("MainWindow", "Công việc"))

        # TAB 3 - INTERACTIONS
        self.t3LiveSrcLabel.setText(_translate("MainWindow", "Livestream (nguồn):"))
        self.t3WorkTimeLabel.setText(_translate("MainWindow", "Work time (phút):"))
        self.t3LiveStatusLabel.setText(_translate("MainWindow", "Trạng thái: chưa kết nối"))
        self.t3WorkTimelineEdit.setValidator(QIntValidator(1, 60))
        self.t3LiveStatusLineEdit.setText("Chưa kết nối!")
        self.t3SaveConfigBtn.setText(_translate("MainWindow", "Lưu"))
        item = self.t3tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Started time"))
        item = self.t3tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Interaction quantity"))
        item = self.t3tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Status"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Tương tác"))


    def open_dialog(self):
        dialog = QDialog()
        # Create layout
        layout = QVBoxLayout(self.actionTab)

        # Create buttons
        button1 = QPushButton('Use Cookie', self.actionTab)
        button1.clicked.connect(self.save_profile_by_cookie)

        button2 = QPushButton('Use Profile', self.actionTab)
        button2.clicked.connect(self.save_profile_by_credentials)

        # Add buttons to layout
        layout.addWidget(button1)
        layout.addWidget(button2)

        dialog.setLayout(layout)

        button_pos = self.saveProfiles.pos()

        # Adjust the position of the dialog
        dialog.move(button_pos.x() + 145, button_pos.y() + 115)

        dialog.exec_()

    def save_profile_by_cookie(self):
        print('Save profile by cookie...')

    def save_profile_by_credentials(self):
        print('Save profile by user-pass...')

    def show_error_dialog(self, err_msg):
        # Create an error message box
        error_dialog = QMessageBox(self.actionTab)
        error_dialog.setIcon(QMessageBox.Critical)
        error_dialog.setWindowTitle('Error')
        error_dialog.setText(err_msg)
        error_dialog.setStandardButtons(QMessageBox.Ok)

        # Show the error dialog
        error_dialog.exec_()



    def updateSelectedRows(self):
        # Get the list of selected rows
        self.selected_rows = set()
        for item in self.tableWidget.selectionModel().selectedRows():
            self.selected_rows.add(item.row())

        # Update the label with the total number of selected rows
        self.selected_rows_count = len(self.selected_rows)
        self.totalSelectedRows.setText(f'(*) Selected accounts: {len(self.selected_rows)}')


    def save_profiles(self):
        current_category = self.category.currentText()
        username_keys  = list(self.accounts[current_category].keys())

        # Get selected items
        selected_rows = set(index.row() for index in self.tableWidget.selectionModel().selectedRows())
        selected_rows = list(selected_rows)

        

        if len(selected_rows) == 0:
            self.show_error_dialog(err_msg='Chưa có tài khoản nào được chọn!')
        elif self.accounts[current_category][username_keys[0]]['proxy'] == '':
            self.show_error_dialog(err_msg='Proxy chưa được thêm vào!!')
        else:

            # Display the selected indices
            for row_i in selected_rows:

                tiktok_login_credential = {
                    "username": self.accounts[current_category][username_keys[row_i]]["username"],
                    "password": self.accounts[current_category][username_keys[row_i]]["password"],
                }

                proxy = self.split_proxies(self.accounts[current_category][username_keys[row_i]]['proxy'])

                tiktok_worker = SeleniumWorker(
                                                facebook_login_credential={},
                                                tiktok_login_credential=tiktok_login_credential,
                                                cookie_str="",
                                                proxy=proxy, profile_id=self.accounts[current_category][username_keys[row_i]]['username'],
                                                tasks=['generate_profile']
                                                )

                '''
                1/1/2024 -
                Connect signals.started and signals.finished 
                to the thread_start and thread_finished functions 
                to update the running_threads, waiting_threads 
                and completed_threads counters
                '''
                tiktok_worker.signals.started.connect(self.thread_started)
                tiktok_worker.signals.finished.connect(self.thread_finished)
                
                tiktok_worker.signals.result.connect(lambda result, row=row_i: self.display_result(result, row))
                tiktok_worker.signals.error.connect(lambda error, row=row_i: self.display_error(error, row))
                tiktok_worker.signals.profile_status.connect(lambda status, row=row_i: self.change_profile_status(status, row))
                tiktok_worker.signals.cookie.connect(lambda cookie, row=row_i: self.change_cookie(cookie, row))

                # Execute the worker in the thread pool
                self.threadpool.start(tiktok_worker)

            
    def thread_started(self):
        self.running_threads += 1
        self.update_labels()

    def thread_finished(self):
        self.running_threads -= 1
        self.completed_threads += 1
        self.update_labels()        

    def update_labels(self):
        running_threads = self.running_threads
        waiting_threads = self.selected_rows_count - (self.running_threads + self.completed_threads)
        completed_threads = self.completed_threads

        self.totalRunningRows.setText(f"Running accounts: {running_threads}")
        self.totalWaitingRows.setText(f"Waiting accounts: {waiting_threads}")
        self.totalCompletedRows.setText(f"Completed accounts: {completed_threads}")

            
    def showContextMenu(self, pos):
        selected_rows = set(index.row() for index in self.tableWidget.selectionModel().selectedRows())

        if len(selected_rows) > 0:
            # Convert the widget coordinates to global coordinates
            global_pos = self.tableWidget.mapToGlobal(pos)

            # Create a context menu
            context_menu = QMenu(self.tableWidget)

            # Add title action (disabled and with a different font)
            title_action = context_menu.addAction("Actions:")
            title_action.setEnabled(False)
            title_font = title_action.font()
            title_font.setBold(True)
            title_action.setFont(title_font)
            title_action.setEnabled(False)

            # Add actions to the context menu
            action_save_profile = QAction("Test profile", self.tableWidget)

            # Connect actions to slots (you can implement your own slots)
            action_save_profile.triggered.connect(lambda: self.test_profile(selected_rows))

            # Add actions to the context menu
            context_menu.addAction(action_save_profile)

            # Show the context menu at the global position
            context_menu.exec_(global_pos)

    def test_profile(self, selected_rows):

        current_category = self.category.currentText()

        row_index = list(selected_rows)[0]
        try:
            if self.accounts[current_category][row_index]['profile_status'] == False:
                return self.show_error_dialog(err_msg='Tài khoản này không tồn tại profile để test!')


            if len(self.accounts[current_category][row_index]['proxy']) == 0:
                return self.show_error_dialog(err_msg='Cần thêm proxy để test profile!')

            proxy = self.split_proxies(self.accounts[current_category][row_index]['proxy'])

            profile_id = self.accounts[current_category][row_index]['uid']

            cookie = self.accounts[current_category][row_index]['cookie']

            facebook_login_credential = {
                    "uid": self.accounts[current_category][row_index]["uid"],
                    "password": self.accounts[current_category][row_index]["password"],
                    "fa_secret": self.accounts[current_category][row_index]["fa_secret"],
                }


            facebook_worker = SeleniumWorker(
                                            facebook_login_credential=facebook_login_credential,
                                            cookie_str=cookie,
                                            proxy=proxy, profile_id=profile_id,
                                            tasks=['test_profile']
                                            )

            facebook_worker.signals.started.connect(self.thread_started)
            facebook_worker.signals.finished.connect(self.thread_finished)
            
            facebook_worker.signals.result.connect(lambda result, row=row_index: self.display_result(result, row))
            facebook_worker.signals.error.connect(lambda error, row=row_index: self.display_error(error, row))
            facebook_worker.signals.profile_status.connect(lambda status, row=row_index: self.change_profile_status(status, row))
            facebook_worker.signals.cookie.connect(lambda cookie, row=row_index: self.change_cookie(cookie, row))

            # Execute the worker in the thread pool
            self.threadpool.start(facebook_worker)

        except Exception as error:
            tb_info = traceback.format_exc()
            print('Có lỗi xảy ra khi test profile:', error, tb_info)

    def on_run_button_clicked(self, row, col):
        current_category = self.category.currentText()

        if len(self.accounts[current_category][row]['proxy']) == 0:
            self.changeCellValue(row=row, col=self.column_order.index('status'), newValue='Lỗi xảy ra: Hãy thêm proxies trước!')
        else:
            # _______________USE SELENIUM-FACEBOOK-WORKER_________________
            facebook_login_credential = {
                "uid": self.accounts[current_category][row]["face_uid"],
                "password": self.accounts[current_category][row]["face_pass"],
                "fa_secret": self.accounts[current_category][row]["face_secret"],
            }

            tds_login_credential = {
                'username': self.accounts[current_category][row]['tds_username'],
                'password': self.accounts[current_category][row]['tds_pass']
            }

            proxy = self.split_proxies(self.accounts[current_category][row]['proxy'])

            facebook_worker = SeleniumWorker(facebook_login_credential=facebook_login_credential,
                                            tds_login_credential=tds_login_credential,
                                            proxy=proxy
                                            )
            facebook_worker.signals.result.connect(lambda result: self.display_result(result, row))
            facebook_worker.signals.error.connect(lambda error: self.display_error(error, row))
            # Execute the worker in the thread pool
            self.threadpool.start(facebook_worker)
    
    def display_result(self, result, row):
        print('result:', result)
        print('row:', row)
        self.changeCellValue(row, self.column_order.index('status'), newValue=str(result))

    def display_error(self, error, row):
        print('error:', error)
        self.changeCellValue(row, self.column_order.index('status'), newValue=f'{error}')

    def change_profile_status(self, status, row):
        current_category = self.category.currentText()
      
        self.changeCellValue(row, self.column_order.index('profile_status'), newValue=status)
        self.accounts[current_category][row]['profile_status'] = True
        


    def change_cookie(self, cookie, row):
        current_category = self.category.currentText()

        self.changeCellValue(row, self.column_order.index('cookie'), newValue=f'{cookie}')
        # change the account's cookie
        self.accounts[current_category][row]['cookie'] = cookie

    def changeCellValue(self, row, col, newValue):
        current_category = self.category.currentText()
        # newValue == 0 or 1 is corresponding change profile_status column
        if newValue == 0:
            new_item = QtWidgets.QLabel()
            pixmap = QPixmap(self.x_mark_img)
            new_item.setPixmap(pixmap)
            new_item.setAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
            self.tableWidget.setCellWidget(row, col, new_item)

            self.accounts[current_category][row]['profile_status'] = False
        elif newValue == 1:
            new_item = QtWidgets.QLabel()
            pixmap = QPixmap(self.check_mark_img)
            new_item.setPixmap(pixmap)
            new_item.setAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
            self.tableWidget.setCellWidget(row, col, new_item)
        else:
            # Create a new item with the desired value
            new_item = QtWidgets.QTableWidgetItem(newValue)

            # Set the new item for the specified cell
            self.tableWidget.setItem(row, col, new_item)


    def add_row(self, row_index, data):
        _translate = QtCore.QCoreApplication.translate
        for column_index, key in enumerate(self.column_order):

            value = data.get(key, "")
            category = data["category"]
            username = data["username"]
            
            if key == "username":
                profile_id = value

            if key == "profile_status":
                # button = QPushButton(f"Run")
                # button.clicked.connect(lambda state, row=row_index, col=column_index: self.on_run_button_clicked(row, col))
                # self.tableWidget.setCellWidget(row_index, column_index, button)

                profile_path = f"./user-profiles/{profile_id}"
                if self.check_profiles_exists(profile_path=profile_path):
                    item = QtWidgets.QLabel()
                    pixmap = QPixmap(self.check_mark_img)
                    item.setPixmap(pixmap)
                    item.setAlignment(Qt.AlignHCenter | Qt.AlignVCenter)

                    self.tableWidget.setCellWidget(row_index, column_index, item)

                    self.accounts[category][username]['profile_status'] = True
                else:
                    self.accounts[category][username]['profile_status'] = False
            else:
                item = QtWidgets.QTableWidgetItem()
                item.setText(_translate("MainWindow", str(value)))
                self.tableWidget.setItem(row_index, column_index, item)


            


    def add_accounts_to_table(self, accounts: dict):
        
        
        self.tableWidget.setRowCount(len(accounts))
        __sortingEnabled = self.tableWidget.isSortingEnabled()

        # Positions of field columns in the data table
        # column_order = ["tds_username", "tds_pass", "face_uid", "face_pass", "cookie", "token", "proxy", "user_agent", "tds_coins",  "status",  "action"]

        for row_index, account_data in enumerate(accounts.values()):
            self.add_row(row_index, account_data)


        self.tableWidget.setSortingEnabled(__sortingEnabled)

        password_delegate = PasswordDelegate()

        # Set format (*) for columns 'password' and 'email_password' 
        self.tableWidget.setItemDelegateForColumn(self.column_order.index('password'), password_delegate)
        self.tableWidget.setItemDelegateForColumn(self.column_order.index('email_password'), password_delegate)    

        print('Added accounts successfully!')

    def add_accounts_to_temp_table(self, accounts: list):
        self.tempTableWidget.setRowCount(len(accounts))
        __sortingEnabled = self.tableWidget.isSortingEnabled()

        for row_index, account_data in enumerate(accounts):
            self.add_row_to_temp_table(row_index, account_data)
        self.tempTableWidget.setSortingEnabled(__sortingEnabled)

        print('Added accounts to the temporary table!')

    def add_row_to_temp_table(self, row_index, data):
        for column_index, cell in enumerate(data):
            item = QtWidgets.QTableWidgetItem(cell)
            self.tempTableWidget.setItem(row_index, column_index, item)

    def add_accounts_from_file(self):
        try:
            # Open file Dialog
            file_name, _ = QFileDialog.getOpenFileName(None, "Open File", "", "All Files (*);;Text Files (*.txt);;JSON Files (*.json)")
            
            # Read file and import to data table
            if file_name:

                file = QFile(file_name)

                # Check the file extension
                file_extension = os.path.splitext(file_name)[1]

                if file_extension == '.txt':
                    if file.open(QFile.ReadOnly | QFile.Text):
                        stream = QTextStream(file)
                        facebook_accounts_content = stream.readAll()
                        # remove first and last space
                        facebook_accounts_content = facebook_accounts_content.strip()

                        account_lines = facebook_accounts_content.split('\n')

                        self.accounts = self.file_preprocessing(account_lines)

                        # Add data to the data table
                        self.add_accounts_to_table(self.accounts)
                        
                        file.close()
                    else:
                        print(f"Error opening file: {file.errorString()}")

                if file_extension == '.json':
                    if file.open(QFile.ReadOnly | QFile.Text):
                        stream = QTextStream(file)
                        fa_accounts_content = stream.readAll()

                        # Parse JSON data using QJsonDocument
                        document = QJsonDocument.fromJson(fa_accounts_content.encode('utf-8'))

                        # Convert QJsonDocument to Python dictionary
                        fa_accounts_dict : dict = json.loads(document.toJson(QJsonDocument.Compact).data().decode('utf-8'))

                        self.accounts = list(fa_accounts_dict.values())

                        # Add data to the data table
                        self.add_accounts_to_table(self.accounts)
                        
                        file.close()

            print('accounts:', self.accounts)

        except Exception as error:
            print(error)

    def file_preprocessing(self, account_lines, account_pos: list) -> None:
        current_category = self.category.currentText()
        accounts_arr = []
        accounts_obj = {}
        account_wrapper_obj = {}
        for index, account_line in enumerate(account_lines):



            account_values = account_line.split('|')

            account_obj = {}
            for item in account_pos:
                account_obj[item[1]] = account_values[item[0]]

            account_obj['category'] = current_category
            

            # account_obj = {
            #     "uid": account_values[0], 
            #     "password": account_values[1],
            #     "fa_secret": account_values[2],
            #     "cookie": account_values[5],
            #     "token": account_values[6],
            #     "email": account_values[3],
            #     "email_password": account_values[4],
            #     "proxy": '',
            #     "status": ''
            #     }
            
            # accounts_arr.append(account_obj)
            accounts_obj[account_obj["username"]] = account_obj

        # self.accounts[current_category] = accounts_arr
        self.accounts[current_category] = accounts_obj
        return None

    def split_proxies(self, proxy_string:str)->dict:
        host, port, username, password = proxy_string.split(':')

        return {'host': host, 'port': port, 'username': username, 'password': password}
    
    def add_proxies_from_file(self):
        try:
            if self.tableWidget.rowCount() == 0:
                self.show_error_dialog(err_msg="Bạn phải thêm accounts trước!")
            else:
                # Open file Dialog
                file_name, _ = QFileDialog.getOpenFileName(None, "Open File", "", "All Files (*);;Text Files (*.txt)")
                    
                # Read file and import to data table
                if file_name:

                    file = QFile(file_name)

                    if file.open(QFile.ReadOnly | QFile.Text):
                        stream = QTextStream(file)
                        proxies_content = stream.readAll()
                        # remove first and last space
                        proxies_content = proxies_content.strip()

                        proxies_lines = proxies_content.split('\n')

                        # Add proxies to accounts
                        
                        count = 0
                        for account in self.accounts:
                            if count > len(proxies_lines) - 1:
                                # reset count to 0
                                count = 0

                            account["proxy"] = proxies_lines[count]
                            
                            # increase count
                            count += 1

                            
                        self.add_accounts_to_table(self.accounts)             

                        file.close()

                        print("Added proxies to accounts successfully!")
                    else:
                        print(f"Error opening file: {file.errorString()}")
        except Exception as error:
            print(error)

    def update_config_days(self, config_json):
        i = 0

        for key in config_json.keys():
            self.configDays.setItemText(i, key)
            i+=1
        
        
    def check_profiles_exists(self, profile_path):
        profile_path = Path(profile_path)

        if profile_path.exists() and profile_path.is_dir():
            return True
        
        return False
    

    def interact_tiktok(self):
        # selected_config_day = self.configDays.currentText()


        # if len(selected_config_day) == 0:
            # self.show_error_dialog(err_msg="You have not added the config yet!")
        # else:
            # print('config_day:', selected_config_day)
        
        if self.tableWidget.rowCount() == 0:
            return self.show_error_dialog(err_msg="Chưa có tài khoản nào được chọn!")
            
        
        return

    
    def convert_data_to_dict(self):
        accounts_arr = self.accounts
        accounts_dict = {}

        for item in accounts_arr:
            key = item['username']

            # remove item with key = status if it exist
            if item.get('status') is not None:
                item.pop('status')

            accounts_dict[key] = item

            

        return accounts_dict
    
    def exportToJson(self):

        if len(self.accounts) == 0:
            return self.show_error_dialog(err_msg="Chưa có dữ liệu nào để xuất file!")

        file_name, _ = QFileDialog.getSaveFileName(None, "Save JSON File", "", "JSON Files (*.json)")

        if file_name:
            accounts = self.convert_data_to_dict()

            with open(file_name, 'w') as json_file:
                json.dump(accounts, json_file, indent=4)
            print(f"Data exported to {file_name}")

    def show_add_accounts_dialog(self):
        # Create a dialog
        self.dialog = QDialog()
        self.dialog.setWindowTitle('Thêm tài khoản')
        self.dialog.setGeometry(450, 180, 1000, 390)  # Set the size of the dialog

        # Create a text edit box
        text_edit = QTextEdit(self.dialog)
        # text_edit.setGeometry(10, 10, 900, 360)

        temp_columns = ["","username", "password", "email", "email_password", "cookie", "token", ]

        self.comboBoxA = QtWidgets.QComboBox(self.dialog)
        self.comboBoxA.setObjectName("comboBoxA")
        self.comboBoxA.addItems(temp_columns)


        self.comboBoxB = QtWidgets.QComboBox(self.dialog)
        self.comboBoxB.setObjectName("comboBoxB")
        self.comboBoxB.addItems(temp_columns)

        self.comboBoxC = QtWidgets.QComboBox(self.dialog)
        self.comboBoxC.setObjectName("comboBoxC")
        self.comboBoxC.addItems(temp_columns)

        self.comboBoxD = QtWidgets.QComboBox(self.dialog)
        self.comboBoxD.setObjectName("comboBoxD")
        self.comboBoxD.addItems(temp_columns)

        self.comboBoxE = QtWidgets.QComboBox(self.dialog)
        self.comboBoxE.setObjectName("comboBoxE")
        self.comboBoxE.addItems(temp_columns)

        self.comboBoxF = QtWidgets.QComboBox(self.dialog)
        self.comboBoxF.setObjectName("comboBoxF")
        self.comboBoxF.addItems(temp_columns)

        self.comboBoxG = QtWidgets.QComboBox(self.dialog)
        self.comboBoxG.setObjectName("comboBoxG")
        self.comboBoxG.addItems(temp_columns)

        self.comboBoxGroup = [self.comboBoxA, self.comboBoxB, self.comboBoxC, self.comboBoxD]



        # The Temporary Table Widget
        self.tempTableWidget = QtWidgets.QTableWidget()
        self.tempTableWidget.setGeometry(QtCore.QRect(180, 130, 411, 192))
        self.tempTableWidget.setObjectName("tableWidget")
        self.tempTableWidget.setColumnCount(6)
        self.tempTableWidget.setRowCount(5)


        item = QtWidgets.QTableWidgetItem()
        self.tempTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tempTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tempTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tempTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tempTableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tempTableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tempTableWidget.setHorizontalHeaderItem(6, item)

        # _translate = QtCore.QCoreApplication.translate
        # item = self.tempTableWidget.verticalHeaderItem(0)
        # item.setText(_translate("MainWindow", "1"))
        # item = self.tempTableWidget.verticalHeaderItem(1)
        # item.setText(_translate("MainWindow", "2"))

        column_widths = [136, 136, 136, 136, 136, 136, 136]
        for i, width in enumerate(column_widths):
            self.tempTableWidget.setColumnWidth(i, width)

        # Caught the text-change's event on text_edit
        text_edit.textChanged.connect(lambda: self.onAccountsTextChanged(text_edit.toPlainText()))

        # Add Save button to close the dialog
        save_button = QPushButton('Lưu', self.dialog)
        save_button.clicked.connect(lambda: self.onSaveAddAccountsClicked(text_edit.toPlainText()))

        # Set up the layout
        self.dialog_layout = QGridLayout()
        self.dialog_layout.addWidget(text_edit, 0, 0, 1, 7)
        self.dialog_layout.addWidget(self.comboBoxA, 1, 0)
        self.dialog_layout.addWidget(self.comboBoxB, 1, 1)
        self.dialog_layout.addWidget(self.comboBoxC, 1, 2)
        self.dialog_layout.addWidget(self.comboBoxD, 1, 3)
        self.dialog_layout.addWidget(self.comboBoxE, 1, 4)
        self.dialog_layout.addWidget(self.comboBoxF, 1, 5)
        self.dialog_layout.addWidget(self.comboBoxG, 1, 6)
        self.dialog_layout.addWidget(self.tempTableWidget, 2, 0, 1, 7)
        self.dialog_layout.addWidget(save_button, 3, 0, 1, 2)

        self.dialog.setLayout(self.dialog_layout)

        # Show the dialog
        self.dialog.exec_()

    def onSaveAddAccountsClicked(self, text):
        current_category = self.category.currentText()

        account_lines = text.splitlines()

        # account_pos used for get columns position from temporary table
        account_pos = []
        for index, combo_box in enumerate(self.comboBoxGroup):
            account_pos.append((index, combo_box.currentText()))

        exist_username = False
        for item in account_pos:
            if item[1] == 'username':
                exist_username = True

        print('account_pos', account_pos)
    
        if not exist_username:
            return self.show_error_dialog(err_msg="Phải chọn ít nhất 1 cột có Username!")
        
        self.file_preprocessing(account_lines, account_pos) #add more account to self.accounts by "key-value pairs"

        # Add data to the data table
        self.add_accounts_to_table(self.accounts[current_category])

        # Automate save deufalt json file
        self.saveJsonFile(self.accounts)

        self.dialog.close()

    def saveJsonFile(self, json_data):
        file_path = "./defaults/data.json"
        try:
            # Write the JSON data to the selected file
            json_object = json.dumps(json_data, indent=4)
            with open(file_path, 'w') as file:
                file.write(json_object)

            print(f'Successfully saved JSON file: {file_path}')
        except Exception as e:
            print(f'Error saving JSON file: {e}')

    def show_add_proxies_dialog(self):
        if self.tableWidget.rowCount() == 0:
            return self.show_error_dialog(err_msg="Bạn phải thêm tài khoản trước khi thêm proxy")

        # Create a dialog
        self.dialog = QDialog()
        self.dialog.setWindowTitle('Thêm proxy')
        self.dialog.setGeometry(450, 180, 1000, 390)  # Set the size of the dialog

        # Create a text edit box
        text_edit = QTextEdit(self.dialog)
        text_edit.setGeometry(10, 10, 900, 360)

        # Add Save button to close the dialog
        save_button = QPushButton('Lưu', self.dialog)
        save_button.clicked.connect(lambda: self.onSaveAddProxiesClicked(text_edit.toPlainText()))

        # Set up the layout
        dialog_layout = QVBoxLayout()
        dialog_layout.addWidget(text_edit)
        dialog_layout.addWidget(save_button)

        self.dialog.setLayout(dialog_layout)

        # Show the dialog
        self.dialog.exec_()

    def onSaveAddProxiesClicked(self, text):

        current_category = self.category.currentText()

        proxy_lines = text.splitlines()

        print('proxy_lines', proxy_lines)
        print('len', len(proxy_lines))

        if len(proxy_lines) != 0:
            count = 0
            for account in self.accounts[current_category].values():
                if count > len(proxy_lines) - 1:
                    # reset count to 0
                    count = 0

                account["proxy"] = proxy_lines[count]
                
                # increase count
                count += 1

                
            self.add_accounts_to_table(self.accounts[current_category])             

            print("Added proxies to accounts successfully!")
        
        
        self.dialog.close()

    def toggle_category_options(self):
        if self.widget.isHidden():
            self.widget.show()
        else:
            self.widget.hide()

    def show_add_new_category(self):
        self.widget.hide()
        dialog = AddCategoryDialog()
        result = dialog.exec_()

        if result == QDialog.Accepted:
            category_input_text = dialog.text_input.text()
            

            # Check if the item already exists in the QComboBox
            checked_index = self.category.findText(category_input_text)

            if checked_index != -1: # Item existed
                return self.show_error_dialog(err_msg=f"Category: '{category_input_text}' đã tồn tại!")


            self.category.addItem(category_input_text)

            # add new category as a key to self.accounts: dict
            self.accounts[category_input_text] = {}

            self.category.setCurrentText(category_input_text)

            print(f'new category: {category_input_text}')

            print(self.accounts)


    def show_confirm_remove_category(self):
        self.widget.hide()
        confirmation = QMessageBox.question(None, 'Confirmation', 'Bạn có chắc chắn muốn xóa?', QMessageBox.Yes | QMessageBox.No, QMessageBox.No)

        if confirmation == QMessageBox.Yes:
            print('You clicked Yes!')
            self.removeCurrentCategory()
        else:
            print('You clicked No.')
  
    def removeCurrentCategory(self):
        # Remove the currently selected item from the QComboBox
        current_index = self.category.currentIndex()
        if current_index != 0:  # Check if an item is selected
            self.category.removeItem(current_index)

    def update_table(self, category):
        if category == "All category":
            all_data = {}
            for account_obj in self.accounts.values():
                all_data.update(account_obj)

            # Show all accounts
            self.add_accounts_to_table(all_data)
        else:
            # show accounts by category that them belong
            self.add_accounts_to_table(self.accounts[category])


    def load_default_data(self):
        print('Loaded default data!')
        # Load and display the contents of the JSON file
        # file_path = "./defaults/data.json"
        # try:
        #     with open(file_path, 'r') as file:
        #         data = file.read()
        #         json_data = json.loads(data)
            
        #         if 'All category' in json_data:
        #             print("json_data['All']=", json_data['All category'])

        # except Exception as e:
        #     print(f"Error loading JSON file: {e}")

    def onAccountsTextChanged(self, text):

        account_lines = text.splitlines()
        processed_accounts = []
        for line in account_lines:
            splitted_line = line.split('|')
            processed_accounts.append(splitted_line)

        if len(processed_accounts) > 0:
            self.add_accounts_to_temp_table(processed_accounts)

    def t3_saveConfig(self):
        print('t3_saveConfig function called!')
        live_src_text = self.t3LiveSrclineEdit.text()
        work_time_text = self.t3WorkTimelineEdit.text()
        if len(live_src_text) <= 0:
            return self.show_error_dialog(err_msg='Vui lòng nhập "Livestream (nguồn)".')
        if live_src_text[0] != "@":
            return self.show_error_dialog(err_msg='"Livestream (nguồn)" không đúng định dạng (@id), hãy thử lại!')
        if len(work_time_text) <= 0:
            return self.show_error_dialog(err_msg='Vui lòng nhập "Work time".')

        self.t3LiveStatusLineEdit.setText("Đang kết nối tới livestream...")


        tiktok_socket_worker = TiktokSocketWorker(live_id="@lphung2712")
        tiktok_socket_worker.signals.result.connect(self.changeLiveConnectionStatus)

        # Execute the worker in the thread pool
        self.threadpool.start(tiktok_socket_worker)

    def changeLiveConnectionStatus(self, msg):
        print('msg', msg)
        self.t3LiveStatusLineEdit.setText(msg)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
